<span style="color: green;"><strong>FİNTAG PROJESİ EDA(keşifçi veri analizi) </strong></span>

In [73]:
# 1. Genel Resim
# 2. Kategorik Değişken Analizi (Analysis of Categorical Variables)
# 3. Sayısal Değişken Analizi (Analysis of Numerical Variables)
# 4. Hedef Değişken Analizi (Analysis of Target Variable)
# 5. Korelasyon Analizi (Analysis of Correlation)

In [74]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### GENEL RESİM

In [75]:
import pandas as pd

df = pd.read_csv(r"C:\Users\melek\Desktop\Muh_tas\sheet1.csv", sep=";")
df = df.copy()
df.head()

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status,loan_int_rate (bins),Age_Group,Income_Bracket,person_income (bins)
0,262,47,110000,MORTGAGE,11,MEDICAL,A,10000,"7,51","0,09",N,13,0,"7,5",6_senior,very_high,110000
1,348,32,87000,MORTGAGE,4,DEBTCONSOLIDATION,A,10000,"7,51","0,11",N,6,0,"7,5",4_middle,high,80000
2,446,33,40000,MORTGAGE,4,PERSONAL,A,10000,"7,51","0,25",N,6,0,"7,5",4_middle,very_low,40000
3,469,26,85000,MORTGAGE,5,MEDICAL,A,10000,"7,51","0,12",N,2,0,"7,5",2_young,high,80000
4,583,22,250000,MORTGAGE,4,EDUCATION,A,10000,"7,51","0,04",N,3,0,"7,5",1_very_young,ultra_high,250000

In [76]:

df.columns = [col.upper() for col in df.columns]
# ID sütununa göre küçükten büyüğe sıralar
df = df.sort_values(by='ID')
df.head()

,ID,PERSON_AGE,PERSON_INCOME,PERSON_HOME_OWNERSHIP,PERSON_EMP_LENGTH,LOAN_INTENT,LOAN_GRADE,LOAN_AMNT,LOAN_INT_RATE,LOAN_PERCENT_INCOME,CB_PERSON_DEFAULT_ON_FILE,CB_PERSON_CRED_HIST_LENGTH,LOAN_STATUS,LOAN_INT_RATE (BINS),AGE_GROUP,INCOME_BRACKET,PERSON_INCOME (BINS)
51256,0,37,35000,RENT,0,EDUCATION,B,6000,"11,49","0,17",N,14,0,11,5_mature,very_low,30000
15763,1,22,56000,OWN,6,MEDICAL,C,4000,"13,35","0,07",N,2,0,13,1_very_young,low,50000
39331,2,29,28800,OWN,8,PERSONAL,A,6000,"8,9","0,21",N,10,0,"8,5",3_middle_young,very_low,20000
48588,3,30,70000,RENT,14,VENTURE,B,12000,"11,11","0,17",N,5,0,11,3_middle_young,medium,70000
39081,4,22,60000,RENT,2,MEDICAL,A,6000,"6,92","0,1",N,3,0,"6,5",1_very_young,medium,60000

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 58645 entries, 51256 to 47713
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          58645 non-null  int64
 1   PERSON_AGE                  58645 non-null  int64
 2   PERSON_INCOME               58645 non-null  int64
 3   PERSON_HOME_OWNERSHIP       58645 non-null  object
 4   PERSON_EMP_LENGTH           58645 non-null  int64
 5   LOAN_INTENT                 58645 non-null  object
 6   LOAN_GRADE                  58645 non-null  object
 7   LOAN_AMNT                   58645 non-null  int64
 8   LOAN_INT_RATE               58645 non-null  object
 9   LOAN_PERCENT_INCOME         58645 non-null  object
 10  CB_PERSON_DEFAULT_ON_FILE   58645 non-null  object
 11  CB_PERSON_CRED_HIST_LENGTH  58645 non-null  int64
 12  LOAN_STATUS                 58645 non-null  int64
 13  LOAN_INT_RATE (BINS)        58645 non-null  object
 14  AGE_GROUP                   58645 non-null  object
 15  INCOME_BRACKET              58645 non-null  object
 16  PERSON_INCOME (BINS)        58645 non-null  int64
dtypes: int64(8), object(9)
memory usage: 8.1+ MB

 **Toplam Gözlem (Satır):**    58 645

 **Toplam Değişken (Sütun):**  17

In [77]:
print(df.shape)

(58645, 17)

In [78]:
df.columns

Index(['ID', 'PERSON_AGE', 'PERSON_INCOME', 'PERSON_HOME_OWNERSHIP',
       'PERSON_EMP_LENGTH', 'LOAN_INTENT', 'LOAN_GRADE', 'LOAN_AMNT',
       'LOAN_INT_RATE', 'LOAN_PERCENT_INCOME', 'CB_PERSON_DEFAULT_ON_FILE',
       'CB_PERSON_CRED_HIST_LENGTH', 'LOAN_STATUS', 'LOAN_INT_RATE (BINS)',
       'AGE_GROUP', 'INCOME_BRACKET', 'PERSON_INCOME (BINS)'],
      dtype='object')

| #  | Sütun Adı                     | Türkçe Karşılığı         | Ne Anlama Gelir? |
|----|------------------------------|--------------------------|------------------|
| 0  | ID                           | Kimlik / Kayıt No        | Her müşteriye atanan benzersiz numara. |
| 1  | PERSON_AGE                   | Kişinin Yaşı             | Kredi başvurusunda bulunan kişinin yaşı. |
| 2  | PERSON_INCOME                | Kişinin Geliri           | Kişinin yıllık toplam kazancı. |
| 3  | PERSON_HOME_OWNERSHIP        | Ev Sahipliği Durumu      | Evin mülkiyet durumu (Kira, İpotek, Kendi evi). |
| 4  | PERSON_EMP_LENGTH            | Çalışma Süresi           | Mevcut iş yerindeki çalışma süresi (yıl). |
| 5  | LOAN_INTENT                  | Kredi Kullanım Amacı     | Kredinin ne amaçla istendiği (Eğitim, Sağlık vb.). |
| 6  | LOAN_GRADE                   | Kredi Derecesi           | Risk seviyesine göre verilen harf notu (A-G). |
| 7  | LOAN_AMNT                    | Kredi Tutarı             | Bankadan talep edilen toplam kredi miktarı. |
| 8  | LOAN_INT_RATE               | Faiz Oranı              | Krediye uygulanan yıllık faiz yüzdesi. |
| 9  | LOAN_PERCENT_INCOME          | Borç/Gelir Oranı         | Kredi miktarının kişinin yıllık gelirine oranı. |
| 10 | CB_PERSON_DEFAULT_ON_FILE    | Geçmiş Temerrüt          | Geçmişte borç ödememe kaydı var mı? (Y/N). |
| 11 | CB_PERSON_CRED_HIST_LENGTH   | Kredi Geçmişi            | Kişinin kaç yıldır kredi sisteminde olduğu. |
| 12 | LOAN_STATUS                  | Kredi Durumu             | Kredi onaylandı mı (1) yoksa reddedildi mi (0)? |
| 13 | LOAN_INT_RATE (BINS)         | Faiz Aralığı             | Faiz oranlarının gruplandırılmış (binning) hali. |
| 14 | AGE_GROUP                    | Yaş Grubu                | Yaşın kategorize edilmiş hali (örn: 20-25). |
| 15 | INCOME_BRACKET               | Gelir Dilimi             | Gelirin seviyelere ayrılmış hali (Düşük, Orta, Yüksek). |
| 16 | PERSON_INCOME (BINS)         | Gelir Aralığı            | Gelirin sayısal olarak aralıklara bölünmüş hali. |

In [92]:
# DF ÖZELLİKLER NELERDİR 
""" 
df.head()
df.tail()
df.shape
df.info()
df.columns
df.index
df.describe().T
df.isnull().values.any()
df.isnull().sum()
"""

def check_df_full(dataframe, head=5):
    print("##################### Shape #####################")
    print(dataframe.shape)
    
    print("\n##################### Types #####################")
    print(dataframe.dtypes)
    
    print("\n##################### Columns ##################")
    print(dataframe.columns)
    
    print("\n##################### Index ####################")
    print(dataframe.index)
    
    print("\n##################### Any Null Values? #########")
    print(dataframe.isnull().values.any())
    
    print("\n##################### Total Null Values #########")
    print(dataframe.isnull().sum())
    print("\n################################################")

# Fonksiyonu çağırmak için:
check_df_full(df)

##################### Shape #####################
(58645, 17)

##################### Types #####################
ID                               int64
PERSON_AGE                       int64
PERSON_INCOME                    int64
PERSON_HOME_OWNERSHIP         category
PERSON_EMP_LENGTH                int64
LOAN_INTENT                   category
LOAN_GRADE                    category
LOAN_AMNT                        int64
LOAN_INT_RATE                  float64
LOAN_PERCENT_INCOME            float64
CB_PERSON_DEFAULT_ON_FILE     category
CB_PERSON_CRED_HIST_LENGTH       int64
LOAN_STATUS                      int64
LOAN_INT_RATE (BINS)            object
AGE_GROUP                       object
INCOME_BRACKET                  object
PERSON_INCOME (BINS)             int64
dtype: object

##################### Columns ##################
Index(['ID', 'PERSON_AGE', 'PERSON_INCOME', 'PERSON_HOME_OWNERSHIP', 'PERSON_EMP_LENGTH', 'LOAN_INTENT', 'LOAN_GRADE', 'LOAN_AMNT', 'LOAN_INT_RATE', 'LOAN_PERCENT_INCOME', 'CB_PERSON_DEFAULT_ON_FILE', 'CB_PERSON_CRED_HIST_LENGTH', 'LOAN_STATUS', 'LOAN_INT_RATE (BINS)', 'AGE_GROUP', 'INCOME_BRACKET', 'PERSON_INCOME (BINS)'], dtype='object')

##################### Index ####################
Index([51256, 15763, 39331, 48588, 39081, 23392, 35029, 22077, 12377, 12686,
       ...
       51800, 20266, 53573,  8834,  1206,  9838,  6243, 10441, 37596, 47713], dtype='int64', length=58645)

##################### Any Null Values? #########
False

##################### Total Null Values #########
ID                            0
PERSON_AGE                    0
PERSON_INCOME                 0
PERSON_HOME_OWNERSHIP         0
PERSON_EMP_LENGTH             0
LOAN_INTENT                   0
LOAN_GRADE                    0
LOAN_AMNT                     0
LOAN_INT_RATE                 0
LOAN_PERCENT_INCOME           0
CB_PERSON_DEFAULT_ON_FILE     0
CB_PERSON_CRED_HIST_LENGTH    0
LOAN_STATUS                   0
LOAN_INT_RATE (BINS)          0
AGE_GROUP                     0
INCOME_BRACKET                0
PERSON_INCOME (BINS)          0
dtype: int64

################################################

In [90]:
def check_df_full(dataframe, head=5):
    print("\n##################### Tail #####################")
    print(dataframe.tail(head))

pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)  # Bölünmeyi engelle
pd.set_option('display.width', 1000)

check_df_full(df)

##################### Tail #####################
          ID  PERSON_AGE  PERSON_INCOME PERSON_HOME_OWNERSHIP  PERSON_EMP_LENGTH LOAN_INTENT LOAN_GRADE  LOAN_AMNT  LOAN_INT_RATE  LOAN_PERCENT_INCOME CB_PERSON_DEFAULT_ON_FILE  CB_PERSON_CRED_HIST_LENGTH  LOAN_STATUS LOAN_INT_RATE (BINS)       AGE_GROUP INCOME_BRACKET  PERSON_INCOME (BINS)
9838   58640          34         120000              MORTGAGE                  5   EDUCATION          D      25000          15.95                 0.21                         Y                          10            0                 15,5        4_middle      very_high                120000
6243   58641          28          28800                  RENT                  0     MEDICAL          C      10000          12.73                 0.35                         N                           8            1                 12,5  3_middle_young       very_low                 20000
10441  58642          23          44000                  RENT                  7   EDUCATION          D       6800          16.00                 0.15                         N                           2            1                   16    1_very_young            low                 40000
37596  58643          22          30000                  RENT                  2   EDUCATION          A       5000           8.90                 0.17                         N                           3            0                  8,5    1_very_young       very_low                 30000
47713  58644          31          75000              MORTGAGE                  2     VENTURE          B      15000          11.11                 0.20                         N                           5            0                   11        4_middle         medium                 70000

In [91]:
def check_df_full(dataframe, head=5):
    print("\n##################### Describe #################")
    print(dataframe.describe([0.01, 0.05, 0.1, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]).T)
 
pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)  # Bölünmeyi engelle
pd.set_option('display.width', 1000)

check_df_full(df)

##################### Describe #################
                              count          mean           std      min        1%        5%       10%       25%       50%       75%        90%        95%        99%         max
ID                          58645.0  29322.000000  16929.497605     0.00    586.44   2932.20   5864.40  14661.00  29322.00  43983.00   52779.60   55711.80   58057.56    58644.00
PERSON_AGE                  58645.0     27.550857      6.033216    20.00     21.00     22.00     22.00     23.00     26.00     30.00      36.00      39.00      49.00      123.00
PERSON_INCOME               58645.0  64046.172871  37931.106978  4200.00  21600.00  28800.00  31200.00  42000.00  58000.00  75600.00  100000.00  120000.00  175000.00  1900000.00
PERSON_EMP_LENGTH           58645.0      4.701015      3.959784     0.00      0.00      0.00      0.00      2.00      4.00      7.00      10.00      12.00      17.00      123.00
LOAN_AMNT                   58645.0   9217.556518   5563.807384   500.00   1286.00   2500.00   3000.00   5000.00   8000.00  12000.00   16000.00   20000.00   25000.00    35000.00
LOAN_INT_RATE               58645.0     10.677874      3.034697     5.42      5.42      6.03      6.76      7.88     10.75     12.99      14.72      15.70      17.49       23.22
LOAN_PERCENT_INCOME         58645.0      0.165779      1.587673     0.00      0.03      0.04      0.06      0.09      0.14      0.21       0.29       0.33       0.42      384.00
CB_PERSON_CRED_HIST_LENGTH  58645.0      5.813556      4.029196     2.00      2.00      2.00      2.00      3.00      4.00      8.00      11.00      14.00      17.00       30.00
LOAN_STATUS                 58645.0      0.142382      0.349445     0.00      0.00      0.00      0.00      0.00      0.00      0.00       1.00       1.00       1.00        1.00
PERSON_INCOME (BINS)        58645.0  60725.893086  38488.910086     0.00  20000.00  20000.00  30000.00  40000.00  50000.00  70000.00  100000.00  120000.00  170000.00  1900000.00

 **Boş Değer Sayısı :**  o  -> boş değer yok

In [ ]:
print(df.isnull().sum())

ID                            0
PERSON_AGE                    0
PERSON_INCOME                 0
PERSON_HOME_OWNERSHIP         0
PERSON_EMP_LENGTH             0
LOAN_INTENT                   0
LOAN_GRADE                    0
LOAN_AMNT                     0
LOAN_INT_RATE                 0
LOAN_PERCENT_INCOME           0
CB_PERSON_DEFAULT_ON_FILE     0
CB_PERSON_CRED_HIST_LENGTH    0
LOAN_STATUS                   0
LOAN_INT_RATE (BINS)          0
AGE_GROUP                     0
INCOME_BRACKET                0
PERSON_INCOME (BINS)          0
dtype: int64

###  Kategorik değişkenleri category yap

In [87]:
# 1. Kategorik değişkenleri category yap
categoric_cols = ['PERSON_HOME_OWNERSHIP', 'LOAN_INTENT', 'LOAN_GRADE', 'CB_PERSON_DEFAULT_ON_FILE']

for col in categoric_cols:
    df[col] = df[col].astype("category")

# 2. Object görünümlü ama aslında sayısal olanları float'a çevir
num_but_car = ['LOAN_INT_RATE', 'LOAN_PERCENT_INCOME']

for col in num_but_car:
    df[col] = (
        df[col].astype(str)
               .str.replace(',', '.', regex=False)
               .str.replace('%', '', regex=False)
    )
    df[col] = pd.to_numeric(df[col], errors="coerce")

# 3. Kontrol: Hedef değişken int olarak kalsın
df['LOAN_STATUS'] = df['LOAN_STATUS'].astype(int)

# 4. Son durum dtype kontrolü
print(df.dtypes)

ID                               int64
PERSON_AGE                       int64
PERSON_INCOME                    int64
PERSON_HOME_OWNERSHIP         category
PERSON_EMP_LENGTH                int64
LOAN_INTENT                   category
LOAN_GRADE                    category
LOAN_AMNT                        int64
LOAN_INT_RATE                  float64
LOAN_PERCENT_INCOME            float64
CB_PERSON_DEFAULT_ON_FILE     category
CB_PERSON_CRED_HIST_LENGTH       int64
LOAN_STATUS                      int64
LOAN_INT_RATE (BINS)            object
AGE_GROUP                       object
INCOME_BRACKET                  object
PERSON_INCOME (BINS)             int64
dtype: object

## KATEGORİK DEĞİŞKEN ANALİZİ

In [93]:
df.groupby(["LOAN_INTENT"]).agg({
    "PERSON_INCOME": ["mean", "median", "min", "max"],
    "LOAN_AMNT": ["mean", "sum", "min", "max"],
    "LOAN_INT_RATE": ["mean", "min", "max"]
})

C:\Users\melek\AppData\Local\Temp\ipykernel_58448\1072870108.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["LOAN_INTENT"]).agg({

                  PERSON_INCOME                              LOAN_AMNT                         LOAN_INT_RATE
                           mean   median    min      max          mean        sum   min    max          mean   min    max
LOAN_INTENT
DEBTCONSOLIDATION  63938.063615  57359.0   9600  1824000   9150.314793   83569825  1000  35000     10.613230  5.42  21.74
EDUCATION          62521.135849  56253.0   5000  1900000   9051.681363  111073182  1000  35000     10.681510  5.42  21.74
HOMEIMPROVEMENT    73456.078344  65000.0  12000   780000  10224.007962   64206770  1000  35000     10.881809  5.42  22.11
MEDICAL            59132.736236  52000.0   4200   828000   8819.990397   96437775   700  35000     10.742830  5.42  21.36
PERSONAL           64852.487220  59381.5   9600  1200000   9239.801318   92545850  1000  35000     10.607075  5.42  22.06
VENTURE            64670.921287  59000.0   9600  1839784   9262.830886   92730200   500  35000     10.604354  5.42  23.22